describe("payments test (with setup and tear-down)", function() {
    beforeEach(function () {
      // initialization logic
      //need value to go into each function in: let billAmt = billAmtInput.value;
  tipAmtInput.value = 10;
  billAmtInput.value = 50;
    });

    //submitPaymentInfo() -- this function's job is to add a payment (using createCurPayment()) to the allPayments object then run appendPaymentTable(curPayment), updateServerTable(), and updateSummary()
    it("should add a payment to allPayments object", function () {


    });
    it("should not add a payment if there's no bill amount", function() {
    

    })
    

    //createCurPayment() -- this function's job is to take the bill and tip values, see if they exist (if not, it returns), if they exist, then return an object with billamt, tip amt, and tippercent (which calls calculateTipPercent)
    it ("should not generate a current payment, should return undefined if no inputs to bill OR tip values", function() {
        //add bill and tip amt
    });
    it ("should generate a current payment if bill AND tip values exit", function () {

    });


  //appendPaymentTable -- this function's job is to create new table rows for each the bill amount, tip amount and tip percentage of the current payment, generated by submit payment info, and append them to the paymentTbody section
    it('should add a new server to allServers on submitServerInfo()', function () {
      
    });
  
    //updateSummary()-- this function's job is to average the 
    it('should add an attribute to the new tr that is created', function () { //you can pass in code for this whole function to use within the expect function 
      
    });
  
  
    afterEach(function() {
      //update all updated objects to equal zero
      //update any changed inputs or htmls to ""
      //update any attributes
      //undo what you already did
    allPayments = {};
    paymentId = 0;
    billAmtInput.value = '';
    tipAmtInput.value = '';

    });
  });
  
  
  